package com.geosecure.attendance.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Maps to: attendance_sessions table.
 * Each QR-code session generated by a faculty member for a class/subject.
 * facultyLatitude/facultyLongitude use BigDecimal to preserve the
 * DECIMAL(10,8)/DECIMAL(11,8) precision needed for the Haversine
 * geofence calculation.
 */
@Entity
@Table(name = "attendance_sessions")
public class AttendanceSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "timetable_id", nullable = false)
    private Timetable timetable;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "faculty_subject_id", nullable = false)
    private FacultySubject facultySubject;

    /** Unique token embedded in the generated QR code. */
    @Column(name = "session_token", nullable = false, unique = true, length = 64)
    private String sessionToken;

    @Column(name = "faculty_latitude", nullable = false, precision = 10, scale = 8)
    private BigDecimal facultyLatitude;

    @Column(name = "faculty_longitude", nullable = false, precision = 11, scale = 8)
    private BigDecimal facultyLongitude;

    @Column(name = "started_at", nullable = false)
    private LocalDateTime startedAt;

    /** started_at + geosecure.qr.expiry-seconds (default 50s). */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Column(name = "is_active")
    private Boolean isActive = true;

    @Column(name = "session_date", nullable = false)
    private LocalDate sessionDate;

    @Column(name = "total_students")
    private Integer totalStudents = 0;

    @Column(name = "present_count")
    private Integer presentCount = 0;

    @Column(name = "created_at", updatable = false, insertable = false)
    private LocalDateTime createdAt;

    public AttendanceSession() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Timetable getTimetable() {
        return timetable;
    }

    public void setTimetable(Timetable timetable) {
        this.timetable = timetable;
    }

    public FacultySubject getFacultySubject() {
        return facultySubject;
    }

    public void setFacultySubject(FacultySubject facultySubject) {
        this.facultySubject = facultySubject;
    }

    public String getSessionToken() {
        return sessionToken;
    }

    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }

    public BigDecimal getFacultyLatitude() {
        return facultyLatitude;
    }

    public void setFacultyLatitude(BigDecimal facultyLatitude) {
        this.facultyLatitude = facultyLatitude;
    }

    public BigDecimal getFacultyLongitude() {
        return facultyLongitude;
    }

    public void setFacultyLongitude(BigDecimal facultyLongitude) {
        this.facultyLongitude = facultyLongitude;
    }

    public LocalDateTime getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(LocalDateTime startedAt) {
        this.startedAt = startedAt;
    }

    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public LocalDate getSessionDate() {
        return sessionDate;
    }

    public void setSessionDate(LocalDate sessionDate) {
        this.sessionDate = sessionDate;
    }

    public Integer getTotalStudents() {
        return totalStudents;
    }

    public void setTotalStudents(Integer totalStudents) {
        this.totalStudents = totalStudents;
    }

    public Integer getPresentCount() {
        return presentCount;
    }

    public void setPresentCount(Integer presentCount) {
        this.presentCount = presentCount;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
